export const APP_ERROR_CODE = {
  INVALID_INPUT: "INVALID_INPUT",
  UNKNOWN_FORMAT: "UNKNOWN_FORMAT",
  PARSE_FAILED: "PARSE_FAILED",
  BALANCE_MISMATCH: "BALANCE_MISMATCH",
  LIMIT_REACHED: "LIMIT_REACHED",
  NOT_FOUND: "NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
